# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5376293317378d72d99ec7f3c2a852f18e74f8482dd614366f3985fc96f46f71a27c61b56970cac5864204c32c00a00df3d6ab86810e0286edfdd05ff5f7b49d

test:
  secret_key_base: f186c6d2de208aef6bef576c5977e821252751e7b496f3812213ec8385f85cd58ce5e25a142e475c67ba20abae5a13c7f0444fd952e66eb0f447808a9ba42143

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
